      SUBROUTINE PRTEVT (BUF, NUP, IDPRUP, XWGTUP, SCALUP, 
     .                   AQEDUP, AQCDUP )

      IMPLICIT NONE

      INTEGER NUP, IDPRUP
      DOUBLE PRECISION XWGTUP, SCALUP, AQEDUP, AQCDUP 
      CHARACTER*200 BUF

      WRITE(BUF,1000) NUP, IDPRUP, XWGTUP, SCALUP, AQEDUP, AQCDUP
      
      BUF=TRIM(BUF)//CHAR(0)

      RETURN 
 1000 FORMAT(I2,I4,4E15.7)

      END
 

      SUBROUTINE PRTPTL (BUF, IDUP, ISTUP, MOTHUP, ICOLUP, PUP, 
     .                   VTIMUP, SPINUP)
     
      IMPLICIT NONE
 
      INTEGER IDUP, ISTUP
      INTEGER MOTHUP(2), ICOLUP(2)
      DOUBLE PRECISION PUP(5)
      DOUBLE PRECISION VTIMUP, SPINUP
      CHARACTER*200 BUF

      WRITE(BUF,1001) IDUP, ISTUP, MOTHUP(1), MOTHUP(2), 
     .                ICOLUP(1), ICOLUP(2), 
     .                PUP(1), PUP(2), PUP(3), PUP(4), PUP(5),
     .                VTIMUP, SPINUP 
    
      BUF=TRIM(BUF)//CHAR(0)
      RETURN 
 1001 FORMAT(I9,I5,2I5,2I5,5E19.11,F3.0,F4.0)

      END

