      PROGRAM TEST

      IMPLICIT NONE

      INTEGER NUPT, IDPRUPT
      DOUBLE PRECISION XWGTUPT, SCALUPT, AQEDUPT, AQCDUPT 

      INTEGER IDUPT, ISTUPT
      INTEGER MOTHUPT(2), ICOLUPT(2)
      DOUBLE PRECISION PUPT(5)
      DOUBLE PRECISION VTIMUPT, SPINUPT
 
      NUPT=5
      IDPRUPT=2
      XWGTUPT=0.8866E-04
      SCALUPT=0.2E+03
      AQEDUPT=0.795E-01
      AQCDUPT=0.115598E+00

      IDUPT=2
      ISTUPT=-1
      MOTHUPT(1)=0
      MOTHUPT(2)=0
      ICOLUPT(1)=502
      ICOLUPT(2)=0
      PUPT(1)=0.0
      PUPT(2)=0.0
      PUPT(3)=0.3109E+03
      PUPT(4)=0.3109E+03 
      PUPT(5)=0.0
      VTIMUPT=0.0
      SPINUPT=-1.0

      CALL PRTEVT(NUPT,IDPRUPT,XWGTUPT,SCALUPT,AQEDUPT,AQCDUPT)
      CALL PRTPTL(IDUPT,ISTUPT,MOTHUPT,ICOLUPT,PUPT,VTIMUPT,SPINUPT)

      END

      SUBROUTINE PRTEVT (NUP, IDPRUP, XWGTUP, SCALUP, AQEDUP, AQCDUP)

      IMPLICIT NONE

      INTEGER NUP, IDPRUP
      DOUBLE PRECISION XWGTUP, SCALUP, AQEDUP, AQCDUP 

      WRITE(*,1000) NUP, IDPRUP, XWGTUP, SCALUP, AQEDUP, AQCDUP

      RETURN 
 1000 FORMAT(I2,I4,4E15.7)

      END

      SUBROUTINE PRTPTL (IDUP, ISTUP, MOTHUP, ICOLUP, PUP, VTIMUP, 
     .                   SPINUP)
     
      IMPLICIT NONE
 
      INTEGER IDUP, ISTUP
      INTEGER MOTHUP(2), ICOLUP(2)
      DOUBLE PRECISION PUP(5)
      DOUBLE PRECISION VTIMUP, SPINUP

      WRITE(*,1001) IDUP, ISTUP, MOTHUP(1), MOTHUP(2), 
     .              ICOLUP(1), ICOLUP(2), 
     .              PUP(1), PUP(2), PUP(3), PUP(4), PUP(5),
     .              VTIMUP, SPINUP 
    
      RETURN 
 1001 FORMAT(I9,I5,2I5,2I5,5E19.11,F3.0,F4.0)

      END

